### ISSUE TITLE
MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $

### ISSUE THREAD

**Issue by junaid55555** [tabby-ai/tabby-android-sdk#13]
whenever we try to create session we got this.

com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
    	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
    	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1465)
    	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:602)
    	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433)
    	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:378)
    	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:40)
    	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
    	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:246)
    	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:156)
    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)

**Comment by miralgolakiya** [comment]
Any Update here?

**Comment by ustadenis** [comment]
Should not be reproducible anymore
